### ISSUE TITLE
Use Support API to raise tickets from Support

### ISSUE THREAD

**Issue by AgaDufrat** [alphagov/support#1422]
## What

Depends on [https://trello.com/c/dPTgPUok/3255-add-raise-zendesk-ticket-feature-to-support-api](https://trello.com/c/dPTgPUok/3255-add-raise-zendesk-ticket-feature-to-support-api "smartCard-inline")

Remove Zendesk-ticket creation / usage of `gds_zendesk` gem from the Support app, and use Support API to raise the tickets instead. New endpoint was added in:

[https://github.com/alphagov/gds-api-adapters/pull/1271/files](https://github.com/alphagov/gds-api-adapters/pull/1271/files "smartCard-inline")

```ruby
SupportApi.raise_support_ticket(
  subject: "Feedback for app",
  tags: ["app_name"]
  body: { }
)
```

Support API should be added  in `app/lib/services.rb`

Tickets are created via gds_zendesk gem in [app/models/zendesk/zendesk_tickets.rb](https://github.com/alphagov/support/blob/main/app/models/zendesk/zendesk_tickets.rb "‌")

## Why

We want to consolidate onto one centralised way of raising support tickets. This will minimise the maintenance overhead if we ever switch away from Zendesk (rumoured to be happening in 2024).
```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/support-api/pull/1003
- [ ] https://github.com/alphagov/support-api/pull/996
- [ ] https://github.com/alphagov/support-api/pull/1006
- [ ] https://github.com/alphagov/support-api/pull/1008
- [ ] https://github.com/alphagov/support/pull/1435
```

**Comment by AgaDufrat** [comment]
WIP Branches:
- Support API: [update-create-support-ticket](https://github.com/alphagov/support-api/compare/update-create-support-ticket)
- Support: https://github.com/alphagov/support/compare/main...use-support-api-to-raise-tickets
